spring:
    datasource:
        url: jdbc:mysql://localhost:3306/dsa
        username: root
        password: laxit
    jpa:
        hibernate:
            ddl-auto: update
        database-platform: org.hibernate.dialect.MySQLDialect
        show-sql: true
